- name: writing yaml script for mysql
  hosts: mysql
  become: yes
  tasks: 
  - name: Disable current version of mysql
    ansible.builtin.command: dnf module disable mysql -y

  - name: copying mysql.repo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install mysql server 
    ansible.builtin.package:
      name: mysql-community-server
      state: present

  - name: Start and enable mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

    